query getCities($city: String, $today: DateTime) {
  city: allCities(filter: { name: $city }, orderBy: name_ASC) {
    id
    name
    weather(filter: { datetime_gte: $today }, orderBy: datetime_ASC, first: 1) {
      id
      datetime
      precipitationMm
      precipitationProbability
      temperatureMax
      temperatureMin
    }
  }
}
